# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('support_worker', models.CharField(max_length=100)),
                ('level_of_support', models.IntegerField()),
                ('last_contact', models.DateTimeField()),
                ('goals_achieved', models.IntegerField()),
            ],
        ),
    ]
