# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTheGo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('support_worker', models.CharField(max_length=100)),
                ('level_of_support', models.IntegerField(verbose_name={1: 'Full Time', 2: 'Part Time', 3: 'Potential', 4: 'Parked'})),
                ('last_contact', models.DateTimeField()),
                ('goals_achieved', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AddServiceUser',
        ),
    ]
