# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTheGo', '0002_auto_20170727_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceuser',
            name='last_contact',
        ),
        migrations.AddField(
            model_name='serviceuser',
            name='last_contact_place',
            field=models.CharField(default='Leeds', max_length=200),
            preserve_default=False,
        ),
    ]
