# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OnTheGo', '0003_auto_20170727_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='last_contact_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
