# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTheGo', '0004_serviceuser_last_contact_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='age',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
